variables:
  CI_REGISTRY_IMAGE: "repo.moh.gov.et:5050/dha-team/ihris" 
  DOCKER_TLS_CERTDIR: ""
docker-build:
  # Official docker image.
  image: docker:19.03.12
  stage: build 
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:backend-$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:backend-latest ./ihris-backend/
    - docker push $CI_REGISTRY_IMAGE:backend-latest
    - docker push $CI_REGISTRY_IMAGE:backend-$CI_COMMIT_SHORT_SHA
    - docker build -t $CI_REGISTRY_IMAGE:backend-$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:ihris-config ./ihris-backend/Dockerfile.ihris.config .
    - docker push $CI_REGISTRY_IMAGE:ihris-config
    - docker push $CI_REGISTRY_IMAGE:ihris-config-$CI_COMMIT_SHORT_SHA
    - docker build -t $CI_REGISTRY_IMAGE:frontend-$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:frontend-latest ./ihris-frontend/
    - docker push $CI_REGISTRY_IMAGE:frontend-latest
    - docker push $CI_REGISTRY_IMAGE:frontend-$CI_COMMIT_SHORT_SHA


  only:
    - master
  tags:
    - front-end